In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[9203, 6602, 1413, 4295],
 [9203, 6602, 1413, 2894],
 [9203, 8444, 1413, 5938],
 [2159, 3475, 4892, 1466, 135],
 [2159, 3475, 4892, 1466, 1678],
 [9728, 9203, 2489, 1413, 1074],
 [8044, 2912, 1920, 1466]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9203 6602 1413 4295]
 [   0    0    0    0 9203 6602 1413 2894]
 [   0    0    0    0 9203 8444 1413 5938]
 [   0    0    0 2159 3475 4892 1466  135]
 [   0    0    0 2159 3475 4892 1466 1678]
 [   0    0    0 9728 9203 2489 1413 1074]
 [   0    0    0    0 8044 2912 1920 1466]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

C:\Users\vsudh\anaconda3\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 441ms/step


array([[[-4.08429988e-02,  3.07682790e-02, -2.63387449e-02,
          4.96593453e-02, -4.28714864e-02, -8.51005316e-03,
         -3.10860761e-02, -1.99061986e-02, -2.37730742e-02,
          2.00646259e-02],
        [-4.08429988e-02,  3.07682790e-02, -2.63387449e-02,
          4.96593453e-02, -4.28714864e-02, -8.51005316e-03,
         -3.10860761e-02, -1.99061986e-02, -2.37730742e-02,
          2.00646259e-02],
        [-4.08429988e-02,  3.07682790e-02, -2.63387449e-02,
          4.96593453e-02, -4.28714864e-02, -8.51005316e-03,
         -3.10860761e-02, -1.99061986e-02, -2.37730742e-02,
          2.00646259e-02],
        [-4.08429988e-02,  3.07682790e-02, -2.63387449e-02,
          4.96593453e-02, -4.28714864e-02, -8.51005316e-03,
         -3.10860761e-02, -1.99061986e-02, -2.37730742e-02,
          2.00646259e-02],
        [-1.25285238e-03, -1.14748590e-02,  3.01431865e-04,
         -2.19744090e-02,  2.71368511e-02,  1.49172880e-02,
          4.81968410e-02, -2.02695616e-02, -9.178865

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 9203, 6602, 1413, 4295])

In [15]:
model.predict(embedded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None